.github/workflows/styleguide.yml
> Little fix to have react-styleguide as doc with github workflow
=> Github Pages doc fix

package.json, styleguide.config.js, yarn.lock
> Adding react-docgen-typescript for parsing typescript components props with styleguide
=> Typescript props on styleguide docs

.github/workflows/deploy.yml
> Do not publish if there are changes only in docs or .github folder
=> Publish conditions

styleguide/components/Logo/index.tsx
=> Doc style fix

.github/workflows/styleguide.yml, styleguide/styles.ts
If the github action React-styleguide is triggered by a pr, it will build the styleguide using the pr code and it will not deploy it. 
If it's triggered by a push on main, it will build with main code and deploy it
=> Doc style fix 2

styleguide/components/Logo/index.tsx, styleguide/styles.ts, styleguide/theme.ts, tsconfig.json
=> I swear it's the last time

tsconfig.json
=> Fix aliases

rollup.config.js
> Add a brief description
> Please add a video or an image of the behavior/changes
=> fix rollup

src/components/icons/README.md, src/components/shims/README.md, src/components/status/README.md, styleguide.config.js, styleguide/styles.ts
=> Sections readme

.github/workflows/pr__first_comment.yml, .github/workflows/pr__labeler.yml
=> get-owners-action integration

.github/workflows/merge__build_docs.yml
=> Test Actions

.github/workflows/pr__first_comment.yml
> Add a brief description
> Please add a video or an image of the behavior/changes
=> testing123

.github/workflows/pr__first_comment.yml, .github/workflows/pr__labeler.yml, README.md
> Add a brief description
> Please add a video or an image of the behavior/changes
=> Testing1234

.github/workflows/pr__first_comment.yml
=> Add Random Reviewers to PRs

src/components/icons/README.md, src/components/shims/README.md, src/components/status/README.md, styleguide.config.js
> README editing for section documentations
=> Sections Documentation

src/components/icons/OSIcon/OSIcon.md, src/components/icons/OSIcon/OSIcon.tsx
=> OSIcon JSDoc

styleguide/components/StyleGuideRenderer.tsx
=> Add octocat

.github/workflows/pr__first_comment.yml
=> Add reviewers automatically

README.md, package.json, styleguide/components/StyleGuideRenderer.tsx
=> Make octocats smaller

.github/workflows/pr__first_comment.yml, .github/workflows/pr__labeler.yml
=> This time should work

.github/workflows/pr__labeler.yml
=> PR labeler fix

src/components/icons/StatusIcon/StatusIcon.md, src/components/icons/StatusIcon/StatusIcon.tsx
> Add a brief description
> Please add a video or an image of the behavior/changes
=> StatusIcon Doc

.eslintrc.json
Use strings instead of integers to set eslint rules
=> Use strings for eslint rults

jest.config.ts, styleguide.config.js, styleguide.config.proxy.js
=> Choose only one test file pattern

bridge/dynamic-plugin-sdk-mocks/useK8sWatchResource.ts
try to get static git pages urls
=> try to get static git pages urls

package.json, rollup.config.js, src/components/Utils/DemoComponent/DemoComponent.tsx, src/components/Utils/DemoComponent/index.ts, src/components/Utils/index.ts, yarn.lock
=> Export demo-comp

bridge/dynamic-plugin-sdk-mocks/getWatchK8sResourceURL.ts, bridge/dynamic-plugin-sdk-mocks/index.ts, bridge/dynamic-plugin-sdk-mocks/useK8sWatchResource.ts, bridge/dynamic-plugin-sdk-mocks/useK8sWatchResourceFS.ts, bridge/dynamic-plugin-sdk-mocks/useK8sWatchResources.ts, bridge/dynamic-plugin-sdk-mocks/useK8sWatchResourcesFS.ts, jest-setup.ts, package.json, public/api/kubernetes/apis/kubevirt.io/v1/namespaces/default/virtualmachines/does-not-exist, src/components/Utils/DemoComponent/__mocks__/vmErrorMock.ts, src/components/Utils/DemoComponent/externalLogic.test.tsx, src/components/Utils/DemoComponent/extrenalLogic.ts
=> Add tests to demoComponent

src/components/Utils/DemoComponent/DemoComponent.tsx
=> Add missing jdoc
